name: Custom Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main # or your default branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # or your required node version

      - name: Install NPM dependencies
        run: npm install

      - name: Set up Ruby and Gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4' # or your required Ruby version
          bundler-cache: true

      - name: Install Jekyll and dependencies
        run: |
          gem install jekyll -v 4.3.4
          gem install bundler
          bundle install

      - name: Build Jekyll Site
        run: jekyll build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2 # Explicitly use v2
        with:
          path: '_site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3