name: Jekyll Deploy V2

on:
  push:
    branches:
      - master
  workflow_dispatch: # Added manual trigger
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Run  manually'
permissions:
  id-token: write
  contents: read
  
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v3 # Updated to v3 for better compatibility
      - name: Set up Node.js v20
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install NPM dependencies
        run: npm install
      - name: Set up Ruby and Gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2' # or your required Ruby version
          bundler-cache: true
      - name: Install Jekyll and dependencies
        run: |
          gem install jekyll -v 4.3.4 # or your jekyll version
          gem install bundler
          bundle install
      - name: Build Jekyll Site
        run: bundle exec jekyll build
      - name: Deploy to GitHub Pages
        uses: jeffreytse/jekyll-deploy-action@v0.6.0
        with:
          provider: 'github'         # Default is github
          token: ${{ secrets.GITHUB_TOKEN }} # It's your Personal Access Token(PAT)
          ssh_private_key: ''        # It's your SSH private key (SSH approach)
          repository: ''             # Default is current repository
          branch: 'gh-pages'         # Default is gh-pages for github provider
          jekyll_src: './'           # Default is root directory
          jekyll_cfg: '_config.yml'  # Default is _config.yml
          jekyll_baseurl: ''         # Default is according to _config.yml
          ruby_ver: ''               # Default is 3.2.0 version
          bundler_ver: ''            # Default is compatible bundler version (~>2.5.0)
          cname: ''                  # Default is to not use a cname
          actor: ''                  # Default is the GITHUB_ACTOR
          pre_build_commands: ''     # Installing additional dependencies (Arch Linux)